name: Vercel Deployment

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js (for Vercel CLI)
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Install Node dependencies
        run: |
          npm ci

      - name: Test FastAPI app
        run: |
          cd orchestration
          python -c "from main import app; print('✅ FastAPI app imports successfully')" || echo "⚠️ FastAPI import test failed"

      - name: Run Python linting (optional)
        run: |
          pip install flake8 black || echo "Linting tools not required for deployment"
          flake8 orchestration/ --max-line-length=88 || echo "Linting completed with warnings"

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./ 